#!/bin/bash

export EDITOR=nvim

export NVM_DIR="$HOME/.nvm"

# Bash prompt variables for OSX
# Previously used, but possibly not needed:
#  /Applications/Xcode.app/Contents/Developer/usr/share/git-core/git-completion.bash \
#  /Applications/Xcode.app/Contents/Developer/usr/share/git-core/git-prompt.sh \

source_files=( \
  /usr/local/opt/git/etc/bash_completion.d/git-prompt.sh \
  /opt/homebrew-cask/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc \
  /opt/homebrew-cask/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc \
  /usr/local/git/current/share/git-core/git-completion.sh \
  /usr/local/git/current/share/git-core/git-prompt.sh \
  $HOME/.nvm_default
)

# Add homebrew-specific completion files, if homebrew is present:
if [[ -n "`which brew`" ]]; then
  # NOTE: brew --prefix $package is hella slow
  brew_prefix=$(brew --prefix)
  export NVM_SH=$brew_prefix/opt/nvm/nvm.sh
  source_files+=(
    $NVM_SH \
    $brew_prefix/opt/git/etc/bash_completion.d/git-prompt.sh
  )
fi

for source_file in "${source_files[@]}"; do
  if [ -f $source_file ]; then
    source $source_file
  fi
done

export CDATA_REPOS="$HOME/repositories"
export CDATA_CONFIG="$CDATA_REPOS/config"

export REPOS_GOOGLE="$CDATA_REPOS/google"
export REPOS_POLYMER_ELEMENTS="$REPOS_GOOGLE/polymerelements"
export REPOS_POLYMER_LABS="$REPOS_GOOGLE/polymerlabs"
export REPOS_POLYMER="$REPOS_GOOGLE/polymer"
export REPOS_PERSONAL="$CDATA_REPOS/personal"

export GOPATH="$CDATA_REPOS/go"

export PATH=$PATH:$HOME/.npm-packages/bin
export PATH=$PATH:node_modules/.bin:$HOME/repositories/go/bin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/.homebrew/bin


# Personal aliases
alias cfg="cd $CDATA_CONFIG"

alias repos="cd $CDATA_REPOS"
alias pe="cd $REPOS_POLYMER_ELEMENTS"
alias pl="cd $REPOS_POLYMER_LABS"
alias p="cd $REPOS_POLYMER"
alias g="cd $REPOS_GOOGLE"
alias togo="cd $GOPATH"
alias cdata="cd $REPOS_PERSONAL"

alias vim='nvim'
alias vi='nvim'

alias ll='ls -alFG'
alias la='ls -AG'
alias l='ls -CFG'

alias set-node-default="bash $CDATA_CONFIG/set-node-default.sh"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"

    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# enable color support in tmux
alias tmux='TERM=xterm-256color tmux'

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=50000
HISTFILESIZE=50000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

export GIT_PS1_SHOWDIRTYSTATE=1

export PS1="\[\e[0;30m\] ᛝ \[\e[1;34m\]\u\[\e[0;30m\]@\[\e[1;30m\]\h\[\e[0;30m\]:\[\e[1;36m\]\W\[\e[1;32m\]\$(__git_ps1)\[\e[0;30m\] ᚦ \[\e[0m\]"

