#!/bin/bash

export EDITOR=nvim

export NVM_DIR="$HOME/.nvm"

if [[ -n "`which brew`" ]]; then
  nvmShell=$(brew --prefix nvm)/nvm.sh
  if [[ -e $nvmShell ]]; then
    source $nvmShell
  fi
fi

export CDATA_REPOS="$HOME/repositories"
export CDATA_SETUP="$CDATA_REPOS/setup"

export REPOS_GOOGLE="$CDATA_REPOS/google"
export REPOS_POLYMER_ELEMENTS="$REPOS_GOOGLE/polymerelements"
export REPOS_POLYMER_LABS="$REPOS_GOOGLE/polymerlabs"
export REPOS_POLYMER="$REPOS_GOOGLE/polymer"
export REPOS_PERSONAL="$CDATA_REPOS/personal"

export GOPATH="$CDATA_REPOS/go"

export PATH=$PATH:$HOME/.npm-packages/bin
export PATH=$PATH:node_modules/.bin:$HOME/repositories/go/bin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$HOME/.cargo/bin


# Personal aliases
alias setup="cd $CDATA_SETUP"
alias update="sh $CDATA_SETUP/setup.sh update"

alias repos="cd $CDATA_REPOS"
alias pe="cd $REPOS_POLYMER_ELEMENTS"
alias pl="cd $REPOS_POLYMER_LABS"
alias p="cd $REPOS_POLYMER"
alias g="cd $REPOS_GOOGLE"
alias togo="cd $GOPATH"
alias cdata="cd $REPOS_PERSONAL"

alias vim='nvim'
alias vi='nvim'

alias ll='ls -alFG'
alias la='ls -AG'
alias l='ls -CFG'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"

    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# enable color support in tmux
alias tmux='TERM=xterm-256color tmux'

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=50000
HISTFILESIZE=50000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Bash prompt variables for OSX
completion_files=( \
  /Applications/Xcode.app/Contents/Developer/usr/share/git-core/git-completion.bash \
  /Applications/Xcode.app/Contents/Developer/usr/share/git-core/git-prompt.sh \
  /usr/local/git/current/share/git-core/git-completion.sh \
  /usr/local/git/current/share/git-core/git-prompt.sh \
  /opt/homebrew-cask/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc \
  /opt/homebrew-cask/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc
)

for completion_file in "${completion_files[@]}"; do
  if [ -f $completion_file ]; then
    source $completion_file
  fi
done

export GIT_PS1_SHOWDIRTYSTATE=1

export PS1="\[\e[0;30m\] ᛝ \[\e[1;34m\]\u\[\e[0;30m\]@\[\e[1;30m\]\h\[\e[0;30m\]:\[\e[1;36m\]\W\[\e[1;32m\]\$(__git_ps1)\[\e[0;30m\] ᚦ \[\e[0m\]"

